# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cricketer',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
